index.md, reference.md
Fix change suggestions from @Adimote.
Fixes: #13, #12, #11, #10, #9, #8, #7, #6, #5, #4
As #3 is a larger change, I'll do that as a separate PR.
=> ABS proof read

index.md, reference.md
=> Remove reference to old tokens

content/api/motor-board.md
Update motor board documentaton for our kit.
=> Update motor board documentation

content/kit/_index.md
=> Remove stray square bracket

config.yml
We now have a wordpress instance, let's use it!
=> Update website link

content/api/_index.md
The docs never said how to run code on the robot, and what you need to have on the USB, now it does!
=> Add details for running code on robot

content/api/power-board.md
Can't use motors without power!
=> Warn turning off power outputs prevents motor board use

.circleci/config.yml, README.md, config.yml, scripts/server.sh
- Fix search :tada:
- Update theme. Likely made little difference, but it's good to stay on top of updates!
- Update Hugo when building on CI
- Disable fast renderer to fix rerender issues
=> General updates

content/api/motor-board.md
Related to https://github.com/sourcebots/robot-api/pull/28
=> Rename motor board power property

content/api/vision.md
Bullet point lists need new lines before
=> Fix Anton's incompetence

content/kit/servo-assembly/GPIO.md
Or rather not. Students will encounter weird behaviour if they try to use them, as the Arduino uses these for serial comms.
Also general capitalisation and things.
=> Document usage of digital pins 0 and 1

content/api/vision.md
=> changed x to y

content/tutorials/editors.md
This is out of scope for our docs
=> Remove comment about vscode vs visual studio

content/kit/batteries/charging.md
=> add clarification to pressing stop button

.spelling, content/kit/webcam.md
Add some docs for the physical webcam
=> Webcam docs

content/kit/_index.md
- Add TeckNet camera
- Update the USB stick count (it should be 2)
- Clean up the ordering of items
- Move the bits we don't mind them keeping into it's own section
The final point is important because we haven't given them a kit checklist this year
=> Update kit list

content/api/editor-support.md
Addresses discussion in https://github.com/sourcebots/docs/pull/76#discussion_r159141323
=> Specify permissions fixes for OSs

config.yml
https://github.com/sourcebots/sb-vision/pull/21#discussion_r162792997
Be more specific about the version of python installed on the Pis
=> Be more specific on python version

content/kit/pi/sd-card.md, content/kit/pi/update-file.md
This is what I was referring to in those comments about list punctuation.
=> Use consistent list punctuation

config.yml, content/updates/_index.md, content/updates/updates/2018-jan.md, layouts/updates/list.html, layouts/updates/single.html
A page will be created with this months release on on Tuesday, once the changelog / `pi-image` build as been finalised.
=> Pi updates

content/tutorials/python-whirlwind-tour.md
Remove reference to if statements earlier in the tutorial, when such mention did not exist.
Fixes #105
=> Remove reference to if statements

content/tutorials/python-whirlwind-tour.md
Changing the extension part of the "Better average calculator" to put the extension after the, incorporation of the later extension into the *extension part*.
=> Update to the tutorial

content/tutorials/intro-to-python.md
I know that when this was discussed in the meeting, use of a table was proposed. 
However, I decided that it would be best to keep the formatting consistent with the Tutorials index page.
=> Improve formatting on Introduction to Python

content/updates/2018-02.md
Add the Changelog for 2018.2.0
**DO NOT MERGE** until we get an image to ship
=> Add 2018.2.0 changelog

content/api/game-state.md, content/updates/2018-03.md
Missing image link from https://github.com/sourcebots/pi-image/pull/24
=> Release 2018.3.0

content/tutorials/python-whirlwind-tour.md
`in` works on things that aren't just strings.
=> Improve explanation of `in`

content/tutorials/python-whirlwind-tour.md
Portable Python is no longer developed.
=> Remove portable python link

content/api/_index.md
There were some residual references to python 3.7 left over, so I changed them to 3.9.6
=> Update python version

.spelling, content/tutorials/python-whirlwind-tour.md
Added some words to the spelling list and changed a few words around
=> Spellchecker fixes

content/tutorials/python-whirlwind-tour.md
My VSCode markdown linter was throwing up lots of errors so I fixed most of them
Mostly just whitespace mixups
=> Remove whitespace

content/api/_index.md, content/api/arduino.md, content/api/game-state.md, content/api/motor-board.md, content/api/power-board.md, content/api/servo-board.md, content/faqs/_index.md, content/kit/_index.md, content/rules/_index.md, content/tutorials/basic-movement.md, content/tutorials/simulator.md
=> Reorder Pages in index

content/api/_index.md
This is Will Barber's edit from before he had to go.
=> Update API index

content/tutorials/basic-movement.md
hopefully I fixed the code now
=> Basic movement fix

content/faqs/_index.md
Fixes https://github.com/sourcebots/docs/issues/158
=> s/sportsmanship/sporting conduct/

content/api/ultrasound.md, content/robots/crane.md, content/robots/forklift.md, content/robots/physical.md
There's no docs on how to access the analogue pins
=> Explain analogue pins

.spelling, content/robots/forklift.md
=> Fix radius

docs/.pages, docs/api/vision/index.md, docs/resources/index.md
There are a few misc things competitors may need to download during the competition. This creates a single page we can list them on.
=> Add resources page

docs/programming/power-board.md
It's nicer for humans this way
=> Swap buzz argument order

.spelling, docs/tutorials/labs/python.md
This might be a better introduction than farmbot for some.
=> Add link to farmbot
