index.md
reference.md

- _API_ should be upper case
- Cleanup code examples
- Correct Spelling
- Highlight variables
- General Cleanup

Proofread Docs

---

content/api/_index.md

Motivation behind: https://github.com/sourcebots/docs/pull/25/commits/243d3e01b07ec8394f9bf5584efe2818e4640b3c
Move reference to getting serial numbers to the main API page, rather than specifying it in each board page

All boards have serial numbers

---

content/simulator/_index.md

Due to time restraints, we're not shipping a simulator instantly, so we can remove this placeholder page.
If we decide we do want to ship it later, the page can be restored.

Remove simulator page

---

config.yml
content/api/_index.md
content/tutorials/python-whirlwind-tour.md
layouts/shortcodes/python_version.html

Specify the version of python we're using. The default in stretch is `3.5`, so that's what we're using!

Specify version of python

---

content/kit/wiring.md

Add some useful tips for wiring up kit.

Wiring guide

---

content/tutorials/basic-movement.md

Some of the code samples still used old the -100..100 range for motor power.
This commit updates them to use the new -1..1 range.
This was spotted by a team at kickstart.

tutorials/basic-movement: divide by a hundred

---

content/kit/servo-assembly/GPIO.md

To be precise, it's the Arduino that communicates with the Pi
using digital pins 0 and 1, not the servo shield as this sentence
previously implied.
This commit also slightly improves the wording of this sentence.

Clarify notice about reserved servo assembly pins

---

shell.nix

This allows users running the Nix package manager to instantly get
an environment containing `hugo` and `npm` by running `nix-shell shell.nix`.
Includes a version check for `hugo >= 0.30`. This is important because
the current stable release of the Nix package set (17.09) ships version 0.29,
which doesn't meet our minimum requirements. Unfortunately I haven't
managed to get this to print anything nicer than "assertion failed"
when the version check fails.

Add a Nix environment definition

---

README.md

`npm` is only needed for tests (specifically spell checker), so it's not necessary to have to build the site.
@kierdavis not sure if `nix` supports some kind of _test dependency_ entry?

Specify npm is only for tests

---

shell.nix

nodejs is only required to run the test suite.
Follows on from #81.

shell.nix: make test-only dependencies optional

---

content/api/power-board.md

Lifted from https://github.com/sourcebots/docs/pull/35#discussion_r158022797

Link to source of BUZZ_NOTES as an alternative to printing

---

layouts/partials/favicon.html
layouts/partials/logo.html

Means the domain it's hosted on isn't baked in, and can be flexible.
https://gohugo.io/functions/relurl/#readout

Stop baking baseurl in exported site

---

config.yml

Now that docs have moved to netlify (#83), we can swap the base url to be `https` 🎉

Change baseurl to https

---

content/api/vision/_index.md
content/api/vision/coordinates.md

Drops references to the legacy "polar" co-ordinate space which is being deprecated, in preparation for the addition of the new "spherical" co-ordinate space.
This is done as a separate PR for merging into #67, so we can get that out sooner. I'll put up a follow-on PR which restores most of this as the "spherical" support implemented in https://github.com/sourcebots/robot-api/pull/61 and https://github.com/sourcebots/sb-vision/pull/23 shortly.

Vision cleanup no polar

---

content/api/vision/_index.md
content/api/vision/coordinates.md

This reverts commit 06ce18ad5ed64ed209215317a381f5da570ffe6e.
Because we haven't shipped the `spherical` code, or docs, we should still be documenting the `polar` coords, so teams can continue to use the kit.

Revert "Drop all references to polar co-ordiates"

---

config.yml

This breaks broken link tests, as the files dont exist yet in master. This link is unlikely to be used anyway
Fixes tests in #94

Remove edit link

---

.circleci/config.yml
package.json

This expands the command arguments to their full names so that the commands are easier to decipher and introduces a (default) version of the `test` command which doesn't require network access, thus un-breaking it for offline development.

Clarify commands

---

content/api/_index.md

This includes a comment about the code being re-run when the USB drive is reinserted into the robot.
I actually think we can do _much_ better than this; probably by pulling these instructions (including the logs detail) to their own page, though this change is smaller and easier and feels a useful step along the way.

Generalise the instructions on running user code

---

README.md
content/kit/pi/update-file.md
content/tutorials/kit-assembly.md

Pages whose urls can optionally end in a trailing slash have issues with parent-relative links, so avoid them.

Avoid parent issues by only using root-relative links

---

.spelling
content/updates/2018-kickstart.md
content/updates/kickstart-2018.md
layouts/updates/list.html
layouts/updates/single.html

Add an update entry for the kickstart kit.
Also adapted the update templates, so `image` and `update` are optional frontmatter, and won't break if either doesn't exist. This is because we didn't ship an update file at kickstart, as the mechanism wasn't in-place yet.

Add update description for kickstart image

---

.spelling
content/api/servo-assembly/_index.md
content/api/servo-assembly/arduino-commands.md
content/kit/servo-assembly/_index.md

This includes a summary of how to create the command on the Arduino as well as how to call it from Python and the errors which could be thrown.
See https://github.com/sourcebots/robot-api/pull/55 and https://github.com/sourcebots/robotd/pull/35 for the related implementations.
Note: there are some TODOs inline. The ones I think need fixing before we ship are:

Add documentation for custom arduino commands

---

.circleci/config.yml
README.md
netlify.toml
shell.nix

This adds support for a use of `.Get` which we want, though isn't actually the latest at the time of updating (only so that this upgrade is minimal).

Update hugo to 0.33

---

static/CNAME

It's left over from GH-Pages deploy which we don't use anymore

Remove CNAME file

---

.circleci/config.yml
README.md
package-lock.json

Upgrade to node 8, so we can use the `package-lock.json` feature to prevent unpinned dependencies breaking our builds, as they do.

Upgrade to Node 8

---

content/api/servo-assembly/arduino-commands.md
content/api/vision/coordinates.md
layouts/shortcodes/added_in.html

This adds `note` boxes which explain that some of the documented features need a recent update in order to be used, along with a [shortcode](https://gohugo.io/content-management/shortcodes/) which defines the boxes.
These boxes ended up being quite a bit larger than I'd originally imagined, but I think are in-keeping with these docs (I'd originally envisioned these being a simple "New in <version>" line, like what you see in the Python docs).
Reviewers: please consider whether the boxes are suitable, both in terms of consistency and whether they're likely to be noticed.
Depends on #107.

Mention when features were added

---

content/api/vision/_index.md
content/api/vision/marker-ids.md

https://trello.com/c/tHwRNdfo/63-deprecate-remove-iswallmarker-istokenmarker-methods
As agreed, we are deprecating is_wall_marker and is_token_marker and encouraging the use of marker.id instead of these two methods.
Code removed in https://github.com/sourcebots/robot-api/pull/93

Removed is_wall_marker/is_token_marker

---

content/tutorials/simulator.md

This page should be considered temporary, and will only last for the duration of Smallpeice 2018

Add page on simulator, with download link

---

content/api/power-board.md
content/kit/power-board.md

Documents the separate power output control API implemented by https://github.com/sourcebots/robot-api/pull/97 as extended by https://github.com/sourcebots/robot-api/pull/101.

Separate power output control

---

.spelling
content/api/arduino.md
content/api/ultrasound.md

Covered simulator differences, analogue + digital IO.
Need to make changes to `arduino.md:31` to match @Adimote 's changes once the virtual robot docs are complete

Add virtual Arduino docs

---

content/api/arduino.md
content/api/servos.md
content/robots/_index.md
content/robots/physical.md

- Document that the physical robot exists
- Document the things which only exist on the physical robot
- Servos

Add a basic physical robot page

---

content/api/arduino.md

Without the trailing slash, links on the robots page don't work properly. We should definitely fix that, however this works around the issue for now.

Add missing trailing slash to this robots docs link

---

content/api/arduino.md
content/api/compass.md
content/api/magnet.md
content/api/servos.md
content/api/ultrasound.md
content/robots/_index.md
content/robots/physical.md

This ensures that they work regardless of any trailing slash on the page that they're rendered. It also makes them more consistent and ensures they match our style (which exists to ensure they always work).
Fixes #184.
Builds on https://github.com/sourcebots/docs/pull/187 to avoid conflicts.

Make internal links root-relative

---

content/api/_index.md
content/tutorials/basic-movement.md

Teams have been writing `from sbot import Robot` as the tutorials say and then wondering why they can't use `AnaloguePin` so I swapped some instances of that with `from sbot import *`

Replace Robot with *

---

docs/api/arduino.md
docs/api/index.md
docs/api/motor-board.md
docs/api/servos.md
docs/api/ultrasound.md
docs/kit/pi.md
docs/kit/power-board.md
docs/kit/servo-assembly/GPIO.md
docs/kit/servo-assembly/ultrasound.md

As part of replacing Hugo, we should replace the warning blocks with [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions)

Replace Hugo shortcodes with mkdocs admonitions

---

docs/tutorials/python-lab.md

Link to the Python lab: https://github.com/sourcebots/python-lab/

Add python lab

---

mkdocs.yml

It causes images to look odd if they don't have backgrounds or have small bits of black text. As they were designed assuming a white background, let's keep to it

Remove dark mode toggle

---

docs/rules/index.md

Blocked on https://github.com/sourcebots/smallpeice-rules/pull/24
The repository for the rules is private, and I'll make it public when we want to publish the rules. We can still merge this beforehand and let the link 404.

Add smallpeice 2023 rules

---

docs/programming/motor-board.md

Triggering over-current protection isn't actually dangerous. So we should adjust this to a warning.

Change Danger to Warning in motor board API

---

docs/programming/index.md
docs/programming/vision/index.md
docs/programming/vision/orientation.md

Docs tweaks
